version: "3.4"

services:
  db:
    image: yadd/lemonldap-ng-pg-database
    environment:
      - POSTGRES_PASSWORD=zz
    healthcheck:
      test: "exit 0"
  base:
    image: yadd/lemonldap-ng-base
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PG_SERVER=db
      - REDIS_SERVER=qwerty
      - FORCE_KEY_REGENERATION=yes
    depends_on:
      db:
        condition: service_healthy
