version: "3.4"

services:
  db:
    image: yadd/lemonldap-ng-pg-database
    environment:
      - POSTGRES_PASSWORD=zz
    healthcheck:
      test: "exit 0"
  base:
    image: yadd/lemonldap-ng-base
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PG_SERVER=db
      - REDIS_SERVER=qwerty
      - FORCE_KEY_REGENERATION=yes
      - OVERRIDE_domain=debian.org
      - OVERRIDE_authChoiceModules={"1_LDAP":"Demo;Demo;Null;;;{}","2_SAML":"SAML;SAML;Null;;;{}"}
      - OVERRIDE_applicationList\.1sample\.catname="Some applications"
      - OVERRIDE_exportedVars\.aa=bb
    depends_on:
      db:
        condition: service_healthy
