version: "3.4"

services:
  auth.example.com:
    image: yadd/lemonldap-ng-full
    environment:
      - LOGGER=stderr
      - USERLOGGER=stderr
  test:
    image: yadd/lemonldap-ng-portal-test
    build:
      context: .
    depends_on:
      auth.example.com:
        condition: service_started
