name: Build and Publish Docker Images

env:
  VERSION: 2.0.16
  PGVERSION: 13
  DEBIANVERSION: bullseye

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build_and_test
        run: ./build-all
        env:
          VERSION: ${{ env.VERSION }}

  build-and-push-pg:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: yadd/lemonldap-ng-pg-database
      - name: Build and push Docker image for pg
        uses: docker/build-push-action@v4
        with:
          context: ./pg
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            yadd/lemonldap-ng-pg-database:latest
            yadd/lemonldap-ng-pg-database:${{ env.PGVERSION }}
            yadd/lemonldap-ng-pg-database:${{ env.PGVERSION }}-bullseye
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-pg-database
          provider: dockerhub
          short_description: 'PostgreSQL database ready to use for LemonLDAP::NG'
          readme_file: 'pg/README.md'

  build-and-push-base:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: yadd/lemonldap-ng-base
      - name: Build and push Docker image for base
        uses: docker/build-push-action@v4
        with:
          context: ./base
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            yadd/lemonldap-ng-base:latest
            yadd/lemonldap-ng-base:stable
            yadd/lemonldap-ng-base:${{ env.VERSION }}
            yadd/lemonldap-ng-base:${{ env.VERSION }}-${{ env.DEBIANVERSION }}
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-base
          provider: dockerhub
          short_description: 'Base image for lemonldap-ng dockers'
          readme_file: 'base/README.md'
      - name: save image
        run: docker save yadd/lemonldap-ng-base:latest >/tmp/base.${{ env.RUNNER_ARCH }}.tar
      - name: Upload llng images as artifact
        uses: actions/upload-artifact@v2
        with:
          name: llng-image
          path: /tmp/base.${{ env.RUNNER_ARCH }}.tar

  build-and-push-portal:
    needs: build-and-push-base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v2
      - name: Load Docker images from previous workflows
        run: docker load --input llng-image/base.${{ env.RUNNER_ARCH }}.tar
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: yadd/lemonldap-ng-portal
      - name: Build and push Docker image for portal
        uses: docker/build-push-action@v4
        with:
          context: ./portal
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            yadd/lemonldap-ng-portal:latest
            yadd/lemonldap-ng-portal:stable
            yadd/lemonldap-ng-portal:${{ env.VERSION }}
            yadd/lemonldap-ng-portal:${{ env.VERSION }}-${{ env.DEBIANVERSION }}
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-portal
          provider: dockerhub
          short_description: 'LemonLDAP::NG Portal'
          readme_file: 'portal/README.md'
      - name: save image
        run: docker save yadd/lemonldap-ng-portal:latest >/tmp/portal.${{ env.RUNNER_ARCH }}.tar
      - name: Upload llng images as artifact
        uses: actions/upload-artifact@v2
        with:
          name: llng-image
          path: /tmp/portal.${{ env.RUNNER_ARCH }}.tar

  build-and-push-cron:
    needs: build-and-push-base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v2
      - name: Load Docker images from previous workflows
        run: docker load --input llng-image/base.${{ env.RUNNER_ARCH }}.tar
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: yadd/lemonldap-ng-cron
      - name: Build and push Docker image for cron
        uses: docker/build-push-action@v4
        with:
          context: ./cron
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            yadd/lemonldap-ng-cron:latest
            yadd/lemonldap-ng-cron:stable
            yadd/lemonldap-ng-cron:${{ env.VERSION }}
            yadd/lemonldap-ng-cron:${{ env.VERSION }}-${{ env.DEBIANVERSION }}
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-cron
          provider: dockerhub
          short_description: 'LemonLDAP::NG maintenance tasks runner'
          readme_file: 'cron/README.md'

  build-and-push-manager:
    needs: build-and-push-base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v2
      - name: Load Docker images from previous workflows
        run: docker load --input llng-image/base.${{ env.RUNNER_ARCH }}.tar
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: yadd/lemonldap-ng-manager
      - name: Build and push Docker image for manager
        uses: docker/build-push-action@v4
        with:
          context: ./manager
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            yadd/lemonldap-ng-manager:latest
            yadd/lemonldap-ng-manager:stable
            yadd/lemonldap-ng-manager:${{ env.VERSION }}
            yadd/lemonldap-ng-manager:${{ env.VERSION }}-${{ env.DEBIANVERSION }}
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-manager
          provider: dockerhub
          short_description: 'LemonLDAP::NG Manager'
          readme_file: 'manager/README.md'

  build-and-push-full:
    needs: build-and-push-portal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v2
      - name: Load Docker images from previous workflows
        run: |
          docker load --input llng-image/base.${{ env.RUNNER_ARCH }}.tar
          docker load --input llng-image/portal.${{ env.RUNNER_ARCH }}.tar
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: yadd/lemonldap-ng-full
      - name: Build and push Docker image for full
        uses: docker/build-push-action@v4
        with:
          context: ./full
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            yadd/lemonldap-ng-full:latest
            yadd/lemonldap-ng-full:stable
            yadd/lemonldap-ng-full:${{ env.VERSION }}
            yadd/lemonldap-ng-full:${{ env.VERSION }}-${{ env.DEBIANVERSION }}
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-full
          provider: dockerhub
          short_description: 'LemonLDAP::NG Portal and Manager'
          readme_file: 'full/README.md'
      - name: save image
        run: docker save yadd/lemonldap-ng-full:latest >/tmp/full.${{ env.RUNNER_ARCH }}.tar
      - name: Upload llng images as artifact
        uses: actions/upload-artifact@v2
        with:
          name: llng-image
          path: /tmp/full.${{ env.RUNNER_ARCH }}.tar

  build-and-push-ssoaas-fastcgi-server:
    needs: build-and-push-base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v2
      - name: Load Docker images from previous workflows
        run: docker load --input llng-image/base.${{ env.RUNNER_ARCH }}.tar
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: yadd/lemonldap-ng-ssoaas-fastcgi-server
      - name: Build and push Docker image for SSOaaS FastCGI Server
        uses: docker/build-push-action@v4
        with:
          context: ./ssoaas-fastcgi-server
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            yadd/lemonldap-ng-ssoaas-fastcgi-server:latest
            yadd/lemonldap-ng-ssoaas-fastcgi-server:stable
            yadd/lemonldap-ng-ssoaas-fastcgi-server:${{ env.VERSION }}
            yadd/lemonldap-ng-ssoaas-fastcgi-server:${{ env.VERSION }}-${{ env.DEBIANVERSION }}
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-ssoaas-fastcgi-server
          provider: dockerhub
          short_description: 'LemonLDAP::NG SSOaaS FastCGI Server'
          readme_file: 'ssoaas-fastcgi-server/README.md'

  build-and-push-dev:
    needs: build-and-push-full
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Test with environment variables
        run: echo $TAG_NAME
        env:
          TAG_NAME: |
            ${{ env.VERSION }}-${{ steps.date.outputs.date }}
            ${{ env.VERSION }}-${{ steps.date.outputs.date }}-${{ env.DEBIANVERSION }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v2
      - name: Load Docker images from previous workflows
        run: docker load --input llng-image/full.${{ env.RUNNER_ARCH }}.tar
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: yadd/lemonldap-ng-dev
      - name: Build and push Docker image for dev
        uses: docker/build-push-action@v4
        with:
          context: ./dev
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            yadd/lemonldap-ng-dev:latest
            yadd/lemonldap-ng-dev:${{ env.VERSION }}-${{ steps.date.outputs.date }}
          label: ${{ steps.meta.outputs.labels }}
